baseURL = 'https://jamosully.github.io/'
languageCode = 'en-us'
title = 'JOSullivan'
theme = 'terminal' 

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
sitename = "JOS"
copyrights = "James O'Sullivan"
defaultList = "global"
paginationLen = 3
projectsURL = "https://example.com"
brief_about = "<center>More to come soon!</center>"

[build]
  list = 'always'
  publishResources = true
  render = 'always'